### PR TITLE
Question images

### PR DESCRIPTION
**Pull request by Jacob-Gramer**
I completed the implementation of user uploading up to 5 images when adding a new answer to a question.  I also did some styling changes to more closely match the example web page

### CODE REVIEW

**Review by tanner-white — CHANGES_REQUESTED** [review]
Can you resolve your merge conflicts before we merge to the main branch please?

**Comment by Jacob-Gramer** [comment]
> Can you resolve your merge conflicts before we merge to the main branch please? (conflict is in css file)

I don't see any conflicts in my file.  Can you leave a note on the line with the conflict?

**Comment by Jacob-Gramer** [comment]
> > Can you resolve your merge conflicts before we merge to the main branch please? (conflict is in css file)
> 
> I don't see any conflicts in my file. Can you leave a note on the line with the conflict?

Actually I found it

**Comment by tanner-white** [comment]
> > > Can you resolve your merge conflicts before we merge to the main branch please? (conflict is in css file)
> > 
> > 
> > I don't see any conflicts in my file. Can you leave a note on the line with the conflict?
> 
> Actually I found it

Thanks!

**Review by tanner-white — APPROVED** [review]

**Pull request merged**
